# Generated by Django 5.1.6 on 2025-03-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='user1234', max_length=50),
        ),
    ]
