# Generated by Django 5.1.6 on 2025-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_time_online',
            field=models.DateTimeField(),
        ),
    ]
